name: produce-latex-document

on:
  push:
    branches:
      - main

jobs: 
  produce-latex:
    runs-on: ubuntu-latest
    steps:
      - name: setup-git-repo
        uses: actions/checkout@v3

  build-latex-doc:
    runs-on: ubuntu-latest
    steps:
        - name: Build the LaTeX document
        - uses: xu-cheng/latex-action@v2
          with:
            root_file: main.tex

  upload:
    runs-on: ubuntu-latest
    needs: [build-latex-doc]
    steps:
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: briefing.pdf